# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /posts/:title
auto: true

# Setup
title:            xvfeng.me
tagline:          'fraserxu blog'
description:      'Thoughts on life and code.'
url:              http://xvfeng.me

author:
  name:           'Fraserxu'
  url:            http://xvfeng.me

paginate:         1

github:
  repo:           https://github.com/fraserxu/fraserxu.github.io