# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Fraser Xu'
tagline:          'Thoughts on life and code.'
description:      'Thoughts on life and code.'
url:              https://fraserxu.me
baseurl:          /
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

author:
  name:           'Fraserxu'
  url:            https://fraserxu.me
  email:          xvfeng123@gmail.com

version:          1.0.0
