markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Fraser Xu
url: http://xvfeng.me
description: A fantastic blog that is fantastic.
twitter: xvfeng
github: fraserxu
gravatar_url: http://en.gravatar.com/userimage/26400562/9cdc30f9fbc7f8f5fd7ac02d2de48f9e.jpeg