# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Fraser Xu'
tagline:          'Thoughts on life and code.'
description:      'Thoughts on life and code.'
url:              https://fraserxu.me
baseurl:          /
paginate:         5

author:
  name:           'Fraserxu'
  url:            https://fraserxu.me
  email:          xvfeng123@gmail.com

version:          1.0.0
